- alias: 'ebusdctl_state'
  trigger:
    platform: state
    entity_id: sensor.ebusdctl_state
  action:
    - service: notify.telegram
      data:
        message: "e-bus state has changed: {{ states('sensor.ebusdctl_state') }}"
