# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# MQTT broker
mqtt:
  broker: 192.168.10.21
  client_id: homeassistant

# Vaillant control
ebusd:
    host: 192.168.10.21
    port: 8888
    name: 'ebusd'
    circuit: 'bai'
    monitored_conditions:
      - 'ReturnTemperature'

# HWC recirculation pump
switch:
  - platform: mqtt
    name: "Sonoff power"
    state_topic: "stat/sonoff-rec-pump/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/sonoff-rec-pump/POWER"
    availability_topic: "tele/sonoff-rec-pump/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
