# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Database location
recorder:
  db_url: 'sqlite://@SMARTHOME_RPI_MNT_DATA@/homeassistant/home-assistant_v2.db'

  # Telegram Bot
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

notify:
  platform: telegram
  chat_id: !secret telegram_chat_id

# MQTT broker
mqtt:
  broker: !secret vaillant_ip
  client_id: homeassistant

# Vaillant control
ebusd:
  host: !secret vaillant_ip
  port: 8888
  name: 'ebusd'
  circuit: 'bai'
  monitored_conditions:
    - 'ReturnTemperature'

# HWC recirculation pump
switch:
  - platform: mqtt
    name: "Sonoff power"
    state_topic: "stat/sonoff-rec-pump/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/sonoff-rec-pump/POWER"
    availability_topic: "tele/sonoff-rec-pump/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
