title: Home
views:
  - badges:
      - binary_sensor.updater
      - person.oleksandr
      - device_tracker.oleksandr_s_nexus_5x
      - sensor.ebusd_returntemp
      - sun.sun
    cards: []
    path: default_view
    title: Home
  - badges: []
    cards:
      - entities:
          - switch.sonoff_power
        title: HWC pump
        type: entities
      - entity: sensor.ebusd_flowtemp
        graph: line
        type: sensor
      - entity: sensor.ebusd_flame
        type: sensor
      - entity: sensor.ebusd_returntemp
        type: sensor
    path: vaillant
    title: Vaillant

