################################################################################
# VRC700f/4 sensors
################################################################################
- platform: mqtt
  name: "ebusd VRC700f/4 room temperature"
  device_class: temperature
  unit_of_measurement: "°C"
  state_topic: "ebusd/b7v/z1RoomTemp"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 20.2
  value_template: >
    {{ '%0.1f' | format(value | float) }}

- platform: mqtt
  name: "ebusd VRC700f/4 flow desired"
  device_class: temperature
  unit_of_measurement: "°C"
  state_topic: "ebusd/b7v/Hc1ActualFlowTempDesired"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 20.2
  value_template: >
    {{ '%0.1f' | format(value | float) }}

- platform: mqtt
  name: "ebusd VRC700f/4 HWC storage temperature"
  device_class: temperature
  unit_of_measurement: "°C"
  state_topic: "ebusd/b7v/HwcStorageTemp"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 59.1
  value_template: >
    {{ '%0.1f' | format(value | float) }}

- platform: mqtt
  name: "ebusd VRC700f/4 day temperature"
  device_class: temperature
  unit_of_measurement: "°C"
  state_topic: "ebusd/b7v/z1DayTemp"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 20.0
  value_template: >
    {{ '%0.1f' | format(value | float) }}

- platform: mqtt
  name: "ebusd VRC700f/4 night temperature"
  device_class: temperature
  unit_of_measurement: "°C"
  state_topic: "ebusd/b7v/z1NightTemp"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 20.0
  value_template: >
    {{ '%0.1f' | format(value | float) }}

- platform: mqtt
  name: "ebusd VRC700f/4 HWC desired temperature"
  device_class: temperature
  unit_of_measurement: "°C"
  state_topic: "ebusd/b7v/HwcTempDesired"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 60.0
  value_template: >
    {{ '%0.1f' | format(value | float) }}

- platform: mqtt
  name: "ebusd VRC700f/4 zone1 heating curve"
  state_topic: "ebusd/b7v/Hc1HeatCurve"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 0.15
  value_template: >
    {{ '%0.2f' | format(value | float) }}

- platform: mqtt
  unique_id: hwc_timer_monday
  name: "ebusd VRC700f/4 HWC timer Monday"
  state_topic: "ebusd/b7v/hwcTimer.Monday"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 07:30;08:30;19:30;22:00;-:-;-:-

- platform: mqtt
  unique_id: hwc_timer_saturday
  name: "ebusd VRC700f/4 HWC timer Saturday"
  state_topic: "ebusd/b7v/hwcTimer.Saturday"
  availability_topic: "ebusd/global/signal"
  payload_available: "true"
  payload_not_available: "false"
  qos: 1
  # value: 07:30;08:30;19:30;22:00;-:-;-:-
