################################################################################
# Force ebusd scanning - triggered on signal going into "true" state
################################################################################
# FIXME: These automations initialize when the binary_sensor.ebusd_signal_acquired
# has already fired on start up, so subscribe via MQTT directly
################################################################################
- alias: 'ebusd force ebusd scanning'
  trigger:
    - platform: mqtt
      topic: "ebusd/global/scan"
      payload: 'finished'
  action:
    - service: mqtt.publish
      data_template:
        topic: ebusd/scan.*/list
        payload: '?'
