################################################################################
# This automation is a part of the workaround described
# https://community.home-assistant.io/t/enhanced-version-of-mqtt-hvac-climate-platform-with-proper-history-chart/75304/31
################################################################################
- alias: 'HVAC mode quirk'
  trigger:
    platform: mqtt
    topic: quirk_ebusd_b7v_Hc1RoomTempSwitchOn_set
  action:
    service: mqtt.publish
    data_template:
      topic: ebusd/b7v/Hc1RoomTempSwitchOn/set
      payload: >
        {% set values = { 'off':'off', 'auto':'modulating', 'heat':'thermostat' } %}
        {{ values[trigger.payload] if trigger.payload in values.keys() else "modulating" }}

- alias: Set heating mode
  trigger:
    platform: state
    entity_id: input_select.heating_mode
  action:
    service: mqtt.publish
    data:
      topic: ebusd/b7v/z1OpMode/set
      # N.B. Setting to "off" will trigger VRC to set activate frost
      # protection mode, e.g. z1ActualRoomTempDesired will be set to
      # something like 5C (depends on VRC setting). This will make
      # thermostat card disable temperature setting as those are above that
      # low temp.
      payload_template: '{{ states("input_select.heating_mode") }}'

- alias: Get heating mode
  trigger:
    platform: mqtt
    topic: ebusd/b7v/z1OpMode
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.heating_mode
      option: '{{ trigger.payload }}'

- alias: 'HVAC HWC mode quirk'
  trigger:
    platform: mqtt
    topic: quirk_ebusd_b7v_HwcOpMode_set
  action:
    service: mqtt.publish
    data_template:
      topic: ebusd/b7v/HwcOpMode/set
      payload: >
        {% set values = { 'off':'off', 'auto':'auto', 'heat':'day' } %}
        {{ values[trigger.payload] if trigger.payload in values.keys() else "off" }}
