substitutions:
  device_name: aux_sonoff
  upper_devicename: Aux sonoff

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

<<: !include wifi.yaml

# Enable logging
logger:

# - Blink slowly (about every second) when a warning is active.
#   Warnings are active when for example reading a sensor value
#   fails temporarily or the WiFi/MQTT connections are disrupted.
# - Blink quickly (multiple times per second) when an error is active.
#   Errors indicate that ESPHome has found an error while setting up.
#   In most cases, ESPHome will still try to recover from the error
#   and continue with all other operations.
# - Stay off otherwise.
status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
- platform: gpio
  name: ${upper_devicename}
  pin:
    number: GPIO12
  id: ${device_name}_relay

binary_sensor:
- platform: gpio
  id: ${device_name}_switch
  pin:
    number: GPIO0
    mode: INPUT_PULLUP
    inverted: True
  on_press:
    - switch.toggle: ${device_name}_relay
# The Status Binary Sensor exposes the node state (if it’s
# connected to via MQTT/native API) for Home Assistant.
- platform: status
  name: ${upper_devicename} status
